<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally><AssemblyName>Guide.Provider</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../Contracts/Contracts.csproj"/><PackageReference Include="DMCBK.PluginSdk" Version="0.1.0-preview.5"/></ItemGroup></Project>