<Project><PropertyGroup><TargetFramework>net10.0</TargetFramework><LangVersion>14.0</LangVersion><Nullable>enable</Nullable><ImplicitUsings>disable</ImplicitUsings><ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally><GenerateDocumentationFile>false</GenerateDocumentationFile><IsPackable>false</IsPackable><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup></Project>