<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><IsPackable>false</IsPackable><GenerateDocumentationFile>false</GenerateDocumentationFile></PropertyGroup><ItemGroup><PackageReference Include="DMCBK.Core"/><PackageReference Include="DMCBK.Commands"/><PackageReference Include="DMCBK.Beacon"/></ItemGroup></Project>